### ISSUE TITLE
Plone 5 issues

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.cover#642]
### Blockers
- [x] `item_icon` expression raises exception (#639)
- [x] `TypeError` accessing Compose view (#641)
- [x] Can't save modified layout (#651)
- [x] Can't configure tile (#667)
- [x] `KeyError: 'imaging_properties'` configuring carousel tile (#781)
- [x] No content chooser button (#668)
- [x] Uncaught TypeError: $(...).tabs is not a function when clicking on Compose (#718)
- [x] Upgrade plone.tiles to 1.8.x (#659)
- [x] Upgrade plone.app.tiles to 2.x (#646)
- [x] Upgrade plone.app.blocks to 3.0.x (#666)
- [x] `AttributeError: 'NoneType' object has no attribute 'absolute_url'` on collective.cover.widgets.textlinessortable (#769)
- [x] `Wrong contained type` on carousel tile (#770)

### Non-blockers
- [ ] Calendar tile does not work (#633)
- [ ] No content type icon on **Add new…** menu (#643)
- [x] Access to Compose and Layout tabs is not evident (#648)
- [x] Broken layouts (#652)
- [ ] Additional TinyMCE formats not showing in RichText Tile visual editor (#743)

**Comment by hvelarde** [comment]
closing this as all blockers have been solved and a new `Plone 5` tag is available.
